server:
  port: 8082
  servlet:
    context-path: /appointment/

spring:
  application:
    name: appointment-service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/appointment
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    br:
      com:
        projeto: DEBUG
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
    root: INFO